spring:
  application:
    name: APIGateWay
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory_service
              uri: lb://InventoryService
              predicates:
                - Path= /api/inventory/**

            - id: order_service
              uri: lb://OrdersService
              predicates:
                - Path= /api/orders/**


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




